### ISSUE TITLE
希望能适配文件夹图标api, dist, doc, assets

### ISSUE THREAD

**Issue by guisturdy** [1217950746/Smile-Theme#1]
如果能实现的话，希望能适配api, dist, doc, assets这些项目里基本都有的且用途明确的文件夹图标。

**Comment by oneo-me** [comment]
老铁你是搞前端的吧，目录图标只打算适配某个语言，或某种工具的，比如 node_modules .vscode 这种目录

**Comment by guisturdy** [comment]
哦哦
